spring:
  application:
    name: profile-filter-service
  servlet:
    multipart:
      file-size-threshold: 2048
      max-file-size: 5MB
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: db.changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
  # parametr for one consumer and producer (example: for education)
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: example-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      acks: 1
      retries: 3
      batch-size: 16384
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  jackson:
    deserialization:
      fail-on-unknown-properties: true
  main:
    banner-mode: "off"
custom_test:
  topic_for_inner_test: inner-test-topic
  list_services_for_filter: education-service, service2, service3


management:
  endpoints:
    web:
      exposure:
        include: health, info
logging:
  level:
    root: info
    by.javaguru.profiler: debug
image:
  storage-dir: ${IMAGES_STORAGE_FOLDER}
curriculum-vitae:
  number-of-user-curriculum-vitae: 5

server:
  port: 9100

